language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

env:
  - PIPENV_IGNORE_VIRTUALENVS=1

before_install:
  - pip install -U pipenv
  - pip install -U codecov

install:
  - pipenv install -d
  # Fix pytest's mising importlib-metadata for Python 3.7
  - if [ "$(pipenv run python --version 2>/dev/null|grep -P "3.(6|7)")" != "" ]; then pipenv install importlib-metadata; fi
  # PyPI publication deps
  - pip install --upgrade setuptools wheel

script:
  - pipenv run python -m flake8
  - pipenv run python -m pytest -c pytest-cov.ini
  - python setup.py sdist bdist_wheel

after_success:
  - codecov

deploy:
  - provider: pypi
    skip_existing: true
    username: "__token__"
    password:
      secure: "CeToEH2K/xUD1o4wxMpT/3g2XtUSD5qaQhz5SbLyEND1dVk3GGvQIZQSkFIqZ2So99L3yAadbn3C81cB2WiXAxa829x3rym9RXgH9r9R+SiVDCSRS0LgccmdQX2Ht2LX2TZRDsJL1ZoYsC5ShpdGspAHPrMEU3JVGThOFOYhPPPF7TaqvUFGrBmbdlvm11B4DqhVIwrkmLT4quHca0taRM3XHWu4tX1tXn2H+FkaQQB3dg/wNbAO1Zyj3Cs+9FvjUUTpCI03TtlYhgP7HiejgcD6tg1rZnZnaoKihfVtNx4KAJvsSqrqP6PG10pVkTGZq/dPqmQYewOLCa1Osz9IqvBCMcWg8yeWcBgsQLn8CK8LychUrMt0bjrXPxEOmqM/zs4FgZaWOgTl5klFY/VHZXLiQlM+aQ6QE07NfH61dfK0N5QuIP40QM2TfOFUb3GWh6N8e3bSZSLIS4fcL50ND0tzsc9TH2pfA5DYlVOXHg0aA4IzHn+ebQ95Yu3ceQKzVOlwC9pX2FokPxlomephpHPR8Ynt2qafeDeFcvok1IEwuPn0cV4G60Bz2YR2VyzbwvA2YLyxrRG8t5DATVju6FF7E+CS2QuNbfKC9fJQy7iQn0zJRGS9y4lhlOpDhWrJMwzycEH6oRYyC4TbyjF67XDnudfnvjnBl0+j09O79mg="
    on:
      tags: true
  - provider: pypi
    server: https://test.pypi.org/legacy/
    skip_existing: true
    username: "__token__"
    password:
      secure: "YaYz4VoAqpH27fMP5aSk+Y4BP+eT5rwMMhsWa02bZ+rp+Sj+QFZTHLbIznTSSp6o/iWW+z2Pu3Ek31FaIGHyEIRXKV0VrVxp+ILNxXuQr2CRScN1ULWYi9hfYCVJ/VGJPTB3tcrHB759KFj7PXUh2fi/ljJv7VI1mQogb5cHYvj2hT5gq2PwE9FQmY3/oy/HySnnTBSle8yMcX2bnOmhHzcMYy65JW8C2wTcc2YPFMzlxGYWS5sUUGFXm7pwY0pCHx7ltLKClp0fUgD6rONR2bP3j5foH4me7phXr3V6hGQ9HMlTYjo2HZg3ftgIGvUqL0VwmCpR+js9SnS2S3iH3svm9qESOE0KRlYSNOBDjCvuUg+qIJuSDH48mTavkP090H4DCwM6lPjfedEIFGeDEgEET+SiaIzxQzolYHgALX7GaKKGmnEKGasnOyaBkK/Mmq5uo1+RhJBkTDtM03rwBEyjvB1k/hJ+p+S3dsVcQWf5TyeZWivP06WrkNFYgZSc8OJPhC1XPVOZ1agdXikJR6NOEi3NajApCTBremZ95ldJcQ/om5o9ahEdPCERNizxFaMl/aZD9vu8e6PxITEWdFaIn5AROZr2gmvmFbwe61Xpia65t38f+MAwHnoWgwLyBWZI/n4lFLjV096hs/iRgwM9oNYwzz5Da1wwpu4I07M="
    on:
      branch: develop
